networks:
  default:
    name: botnet
    external: true
    
services:
  app:
    build: .
    container_name: bot-container-dev
    command: streamlit run ./start.py --server.port 8501
    env_file:
      - .env.dev
    volumes:
      - logs:/app/logs
      - .:/app
      - sqlite-data:/root/.crawl4ai
      - fastembed:/tmp/fastembed_cache/
    ports:
      - "8501:8501"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  # wait for 30 seconds before starting health checks


  promtail:
    image: grafana/promtail:3.2.1
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - logs:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    networks:
      - default
  
  redis:
    container_name: ask_uos_redis
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: >
      --maxmemory 1024mb
      --maxmemory-policy allkeys-lru
      --maxmemory-samples 5
 
  
volumes:
  sqlite-data:
  logs:
  fastembed:
  redis-data:



# find / -name "*.onnx_data" 
# /tmp/fastembed_cache/models--qdrant--multilingual-e5-large-onnx/snapshots/66076b8dc6e367337e3e90e6fb309fb0f3addaf6/model.onnx_data