import asyncio
import json
import uuid
from collections import deque
from typing import Dict, List, Literal, Optional, Union

from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
    ToolMessage,
)
from langchain_core.prompts import PromptTemplate

# from langchain_core.pydantic_v1 import BaseModel, Field, PrivateAttr
from langchain_core.tools import BaseTool
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field, PrivateAttr
from typing_extensions import TypedDict

from src.chatbot.agents.models import Reference, RetrievalResult

# from src.chatbot.agents.utils.agent_helpers import llm, llm_gemini, llm_optional
from src.chatbot.agents.utils.agent_helpers import llm_gemini, llm_optional

# from src.chatbot.agents.utils.agent_helpers import reasoning_llm
from src.chatbot.agents.utils.agent_retriever import (
    _examination_regulations_tool,
    _retriever_his_in_one_tool,
    retrieve_from_infinity_ragflow,
)
from src.chatbot.agents.utils.exceptions import MustContainSystemMessageException
from src.chatbot.prompt.main import (
    get_prompt_length,
    get_system_prompt,
    translate_prompt,
)
from src.chatbot.tools.utils.tool_helpers import ReferenceRetriever
from src.chatbot.tools.utils.tool_schema import (
    HisInOneInput,
    RetrieverInput,
    SearchInputWeb,
)
from src.chatbot.utils.constants import ToolNames
from src.chatbot_log.chatbot_logger import logger
from src.config.core_config import settings
from src.config.models import CollectionNames, VectorDBTypes

OPEN_AI_MODEL = settings.model.model_name
DEBUG = settings.application.debug
# message history limit within the graph
MESSAGE_HISTORY_LIMIT = 7
# Maximum number of tokens for the conversation summary
MAX_TOKEN_SUMMARY = 1000


class State(TypedDict):
    """State management for the graph-based agent.

    Attributes:

        messages: List of messages in the conversation
        search_query: Optional list of queries used for web/db searches
        user_initial_query: Optional string containing the user's initial query
        answer_rejection: Optional string for rejected answers
        score_judgement_binary: Optional string for binary judgement scores
    """

    messages: List[BaseMessage]
    message_history: List[
        BaseMessage
    ]  # to exclude all system messages and messages generated by the agent
    search_query: Optional[List[str]]
    user_initial_query: Optional[str]
    current_date: Optional[str]
    answer_rejection: Optional[str]
    score_judgement_binary: Optional[str]
    about_application: Optional[bool] = (
        False  # To determine which node generates the answer
    )
    teaching_degree: Optional[bool] = (
        False  # To determine which node generates the answer
    )
    tool_messages: Optional[str]
    last_tool_usage: Optional[str]
    rewrite_query: bool = False  # Flag to indicate if the query should be rewritten


class GraphEdgesMixin:
    """Mixin class handling edge routing and decision making in the graph."""

    def route_tools(
        self,
        state: State,
    ) -> Literal["tool_node", "judge_node"]:
        """Route to tool_node if last message has tool calls, otherwise to judge_node.

        Args:
            state: Current state containing messages

        Returns:
            Literal["tool_node", "judge_node"]: Next node to route to

        Raises:
            ValueError: If no messages found in state
        """
        if isinstance(state, list):
            ai_message = state[-1]
        elif messages := state.get("messages", []):
            ai_message = messages[-1]
        else:
            raise ValueError(f"No messages found in input state to tool_edge: {state}")

        if hasattr(ai_message, "tool_calls") and len(ai_message.tool_calls) > 0:
            return "tool_node"
        return "judge_node"

    def route_end(self, state: State) -> Union[Literal["agent_node"], Literal[END]]:
        """Route to agent_node if hallucination check fails, otherwise to END.

        Args:
            state: Current state

        Returns:
            Union[Literal["agent_node"], Literal[END]]: Next node to route to
        """
        if state["pass_hallucinate_check"] == "no":
            return "agent_node"
        return END

    def grade_documents(self, state: State) -> Literal["generate", "rewrite"]:
        """Evaluate if retrieved documents are relevant to the query.

        Args:
            state: Current state

        Returns:
            Literal["generate", "rewrite"]: Decision on document relevance
        """

        tool_messages = state.get("tool_messages", "")
        if len(tool_messages) < 10:
            logger.debug("[LANGGRAPH] GRADE DOCUMENTS EDGE: No tool messages found")
            return "rewrite"

        tool_query = " ".join(state["search_query"])

        class GradeResult(BaseModel):
            """Binary score for document relevance check."""

            binary_score: str = Field(
                description=translate_prompt()["grader_binary_score"]
            )
            reason: str = Field(
                description="Back up your decision with a short explanation"
            )
            # relevant_paragraphs: Optional[str] = Field(
            #     description="From the retrieved documents, which paragraphs are relevant to answer the user query? Extract all relevant paragraphs from the retrieved documents."
            # )

        llm_with_str_output = self._llm.with_structured_output(GradeResult)
        prompt = PromptTemplate(
            template=translate_prompt()["grading_llm"],
            input_variables=["context", "question"],
        )
        chain = prompt | llm_with_str_output
        scored_result = chain.invoke(
            {
                "question": f'{state["user_initial_query"]}, {tool_query}',
                "context": tool_messages,
            }
        )

        try:
            # score = scored_result.binary_score.lower()
            score = scored_result.binary_score.lower()
            if score.lower() in ["yes", "ja"]:
                # TODO Further process the relevant paragraphs
                # self._clean_tool_message = scored_result.relevant_paragraphs
                logger.debug(
                    f"[LANGGRAPH][GRADE DOCUMENTS EDGE] DECISION: DOCS RELEVANT. Reason: {scored_result.reason}"
                )
                if state.get("teaching_degree", False):
                    return "generate_teaching_degree_node"

                elif state.get("about_application", False):
                    return "generate_application"
                else:
                    return "generate"

            else:
                logger.debug(
                    f"[LANGGRAPH][GRADE DOCUMENTS EDGE] DECISION: DOCS NOT RELEVANT. Reason: {scored_result.reason}"
                )
                return "rewrite"
        except Exception as e:
            logger.error(
                f"[LANGGRAPH][GRADE DOCUMENTS EDGE] Error occurred while grading documents: {e}"
            )
            raise e

    def judge_agent_decision(
        self, state: State
    ) -> Union[Literal["agent_node"], Literal[END]]:
        """Judge if agent's decision to not use tools was appropriate.

        Args:
            state: Current state containing messages and judgement score

        Returns:
            Union[Literal["agent_node"], Literal[END]]: Next node based on judgement
        """
        score = state.get("score_judgement_binary", "")
        if score == "yes":
            # google
            self._agent_direct_msg = state["messages"][-1].content[0]["text"]
            # openai
            # self._agent_direct_msg = state["messages"][-1].content
            return END
        return "agent_node"


class GraphNodesMixin:
    """Mixin class handling node operations in the graph."""

    def _extract_tool_info(self, retrieval_result: List[RetrievalResult]):
        outputs_txt = ""
        search_query = []
        for result in retrieval_result:
            if isinstance(result, Exception):
                logger.error(f"Tool call failed: {result}")
                continue
            if result.source_name == CollectionNames.FAQ:
                unique_refs = {item.url_reference_askuos for item in result.reference}
                self._visited_links += list(unique_refs)
            elif result.source_name == (
                CollectionNames.EXAMINATION_REGULATIONS
                or CollectionNames.TROUBLESHOOTING
            ):
                self._visited_docs.docs_references = [*result.reference]

            # web search
            else:
                self._visited_links += result.reference

            outputs_txt += result.result_text + "\n\n"
            search_query.append(result.search_query)

        return outputs_txt, search_query

    @staticmethod
    def create_tools() -> List:
        """Create and configure tools for the chatbot agent.

        Returns:
            List[BaseTool]: Configured tools for the agent
        """
        from langchain_classic.tools import StructuredTool

        # from src.chatbot.tools.search_web_tool import search_uni_web
        from src.chatbot.tools.search_web_tool import async_search

        return [
            StructuredTool.from_function(
                name=ToolNames.TROUBLESHOOTING_TOOL,
                coroutine=_retriever_his_in_one_tool,
                description=translate_prompt()["HISinOne_troubleshooting_questions"],
                args_schema=HisInOneInput,
                handle_tool_errors=True,
            ),
            StructuredTool.from_function(
                name=ToolNames.EXAMINATION_REGULATIONS_TOOL,
                coroutine=_examination_regulations_tool,
                description=translate_prompt()["examination_regulations"],
                args_schema=RetrieverInput,
                handle_tool_errors=True,
            ),
            StructuredTool.from_function(
                name=ToolNames.SEARCH_WEB_TOOL,
                coroutine=async_search,
                description=translate_prompt()["description_university_web_search"],
                args_schema=SearchInputWeb,
                handle_tool_errors=True,
            ),
        ]

    @staticmethod
    def filter_messages(messages: List[BaseMessage], k: int) -> List[BaseMessage]:
        """Filter messages to keep only the last k messages.

        Args:
            messages: List of messages to filter
            k: Number of messages to keep

        Returns:
            List[BaseMessage]: Filtered messages
        """
        if len(messages) <= k:
            return messages

        if isinstance(messages[0], SystemMessage):
            # append system message to the beginning of the list
            return [messages[0]] + messages[-k:]
        else:
            return messages[-k:]

    def agent_node(self, state: State) -> Dict:
        """Decide course of action.

        Args:
            state: Current state containing messages

        Returns:
            Dict: Updated state with agent response
        """
        messages = state.get("messages", [])

        filtered_messages = self.filter_messages(messages, MESSAGE_HISTORY_LIMIT)
        if not isinstance(filtered_messages[0], SystemMessage):
            raise MustContainSystemMessageException(
                "The first message in the conversation must be a SystemMessage."
            )
        response = self._llm_with_tools.invoke(filtered_messages)
        return {
            "messages": filtered_messages + [response],
            "search_query": [],
        }

    def judge_node(self, state: State) -> Dict:
        """Evaluate if agent's decision to not use tools was appropriate.

        Args:
            state: Current state

        Returns:
            Dict: Updated state with judgement result
        """

        logger.debug("[LANGGRAPH][JUDGE NODE] Evaluating agent's decision to use tools")

        class JudgementResult(BaseModel):
            """Result of agent's tool usage judgement."""

            judgement_binary: Literal["yes", "no"] = Field(
                description="The agent must use a Tool 'yes', or 'no'"
            )
            reason: str = Field(
                description="Back up your decision with a short explanation"
            )

        llm_with_str_output = self._llm.with_structured_output(JudgementResult)
        prompt = PromptTemplate(
            template="""
               Your role is to evaluate whether an agent's choice not to utilize a tool was justifiable in a given interaction. 
            Tools are fundamental in ensuring responses are factual and free from errors (e.g., Hallucinations). 
            The agent must use the tools at its disposal to address user queries, rather than defaulting to its pre-trained knowledge. 
            **However**, there are specific scenarios where not using a tool is appropriate:

                1. When the agent needs to ask the user for more information or clarification.
                2. When the agent acknowledges or greets the user.
                3. When the agent informs the user that it can only respond to queries related to university matters.
                
                ### Evaluation Task:
                The agent has decided not to use a tool. Is the agent's decision correct?.  Provide a binary response of 'yes' or 'no':
                    - 'no': The agent incorrectly avoided using a tool and should have done so.
                    - 'yes': The agent's decision was appropriate, and utilizing a tool was unnecessary.
                
                Offer a rationale for your decision. Below, you will find the agent's message and the user's query:

                Agent (AI message):
                {context}

                User Query:
                {question}
            """,
            input_variables=["context", "question"],
        )

        chain = prompt | llm_with_str_output
        score = chain.invoke(
            {"question": state["user_initial_query"], "context": state["messages"][-1]}
        )

        if score.judgement_binary.lower() == "no":
            msg = [HumanMessage(content=translate_prompt()["use_tool_msg"])]
            logger.debug(
                f"[LANGGRAPH][JUGE NODE] The agent should have used a tool. Reason: {score.reason}"
            )
            return {
                "messages": state["messages"] + msg,
                "score_judgement_binary": score.judgement_binary,
            }

        return {"score_judgement_binary": score.judgement_binary}

    async def tool_node(self, state: Dict) -> Dict:
        """Process tool calls."""

        # from src.chatbot.tools.search_web_tool import search_uni_web
        from src.chatbot.tools.search_web_tool import async_search

        # Clear the list of visited links
        # self._visited_links = []--> done in ask_uos_chat.py
        if messages := state.get("messages", []):
            message = messages[-1]
        else:
            raise ValueError("No message found in input")

        # outputs = []
        about_application = False
        teaching_degree = False
        self._visited_docs.clear()
        tool_tasks = []  # gather later with asyncio

        # TODO: FAQ support only available in RAGFLOW. Needs to be done with Milvus
        if (
            state.get("rewrite_query", False)
            and settings.vector_db_settings.type
            == VectorDBTypes.INFINITY_RAGFLOW  # Infinity RAGFlow
        ):
            # if the agent is in the rewrite state, try to find answer in FAQs

            tool_tasks.append(
                retrieve_from_infinity_ragflow(
                    collection_name=CollectionNames.FAQ.value,
                    query=message.tool_calls[0]["args"].get("query"),
                    extract_reference_url=True,
                )
            )

        for tool_call in message.tool_calls:

            # TODO Write test for this
            if tool_call["name"] == ToolNames.SEARCH_WEB_TOOL:
                about_application = tool_call["args"].get("about_application", False)
                teaching_degree = tool_call["args"].get("teaching_degree", False)
                tool_call["args"]["do_not_visit_links"] = self._visited_links
                tool_call["args"]["agent_executor"] = self

                # TODO IF no results are found, the tool result is empty and the agent should generate a new query and search again
                # TODO even when no results are found, the entire graph executes e.g. grade_documents edge

                tool_tasks.append(async_search(**tool_call["args"]))

            # TODO: Unify all vector db based tools. They all should return the same format (text,(source, page))
            elif tool_call["name"] == ToolNames.EXAMINATION_REGULATIONS_TOOL:

                tool_tasks.append(_examination_regulations_tool(**tool_call["args"]))

            elif tool_call["name"] == ToolNames.TROUBLESHOOTING_TOOL:

                tool_tasks.append(_retriever_his_in_one_tool(**tool_call["args"]))

            # tool_m = ToolMessage(
            #     content=json.dumps(tool_result),
            #     name=tool_call["name"],
            #     tool_call_id=tool_call["id"],
            # )

        # Call tools
        retrieval_results: RetrievalResult = await asyncio.gather(
            *tool_tasks, return_exceptions=True
        )
        outputs_txt, search_query = self._extract_tool_info(retrieval_results)
        # TODO Sometines the agent calls several tools and the tokens surpass the defined context window. Do summarization here.

        last_tool_usage = state["messages"][-1].additional_kwargs
        state["messages"] = state["messages"][:-1]  # remove the last AI message

        return {
            # "tool_messages": outputs_txt + faq_content,
            "tool_messages": outputs_txt,
            "last_tool_usage": last_tool_usage,  # last ai message with previous tool usage
            "search_query": search_query,
            "about_application": about_application,
            "teaching_degree": teaching_degree,
        }

    def rewrite(self, state):
        """
        Instruct the agent to rephrase the question.

        Args:
            state (messages): The current state

        Returns:
            dict: The updated state with re-phrased question
        """

        user_query = state["user_initial_query"]

        # TODO delete previous tool messages as they do not inform the users query
        # TODO the state cannot be modified in this way because of the reducder
        # messages = state["messages"] = [
        #     i for i in state["messages"] if not isinstance(i, ToolMessage)
        # ]

        msg = [
            HumanMessage(
                content=translate_prompt()["rewrite_msg_human"].format(
                    user_query,
                    state["last_tool_usage"],
                )
            )
        ]

        # delete the previous ai message
        messages = state["messages"]
        messages = messages[:-1]
        return {"messages": messages + msg, "rewrite_query": True}

    def generate_helper(self, state, system_message_generate):

        messages_history = state.get("message_history", [])
        if messages_history:
            filtered_messages_history = self.filter_messages(
                messages_history, MESSAGE_HISTORY_LIMIT
            )
            message_deque = deque(filtered_messages_history)

            if isinstance(message_deque[0], SystemMessage):
                message_deque.popleft()
                message_deque.appendleft(system_message_generate)
            else:
                message_deque.appendleft(system_message_generate)

            # the last message should be the Human message
            if isinstance(message_deque[-1], AIMessage):
                message_deque.pop()

            if not isinstance(message_deque[0], SystemMessage):
                raise MustContainSystemMessageException(
                    "The first message in the conversation must be a SystemMessage."
                )
            response = self._llm.invoke(list(message_deque))
        else:
            logger.warning(
                "[LANGGRAPH] No messages history found. Using system message only for generation."
            )
            response = self._llm.invoke([system_message_generate])
        return {"messages": messages_history + [response]}

    def generate(self, state: State) -> Dict:
        """Generate final answer based on retrieved documents.

        Args:
            state: Current state

        Returns:
            Dict: Updated state with generated response
        """
        logger.debug("[LANGGRAPH][GENERATE NODE] Generating answer")

        # tool_message = self._clean_tool_message or state.get("tool_messages", None)
        tool_message = state.get("tool_messages", None)
        system_message_generate = SystemMessage(
            content=translate_prompt()["system_message_generate"].format(
                state.get("current_date", ""),
                state.get("search_query", ""),
                tool_message,
            )
        )
        # self._clean_tool_message = None
        return self.generate_helper(state, system_message_generate)

    def generate_application(self, state: State) -> Dict:

        logger.debug(["[LANGGRAPH][GENERATE APPLICATION NODE] Generating answer"])
        # tool_message = self._clean_tool_message or state.get("tool_messages", None)
        tool_message = state.get("tool_messages", None)
        system_message_generate = SystemMessage(
            content=translate_prompt()["system_message_generate_application"].format(
                state.get("current_date", ""),
                state.get("search_query", ""),
                tool_message,
            )
        )
        # self._clean_tool_message = None
        return self.generate_helper(state, system_message_generate)

    def generate_teaching_degree_node(self, state: State) -> Dict:
        """Generate answer for teaching degree related queries.

        Args:
            state: Current state

        Returns:
            Dict: Updated state with generated response
        """
        logger.debug("[LANGGRAPH][GENERATE TEACHING DEGREE NODE] Generating answer")
        # tool_message = self._clean_tool_message or state.get("tool_messages", None)
        tool_message = state.get("tool_messages", None)
        system_message_generate = SystemMessage(
            content=translate_prompt()[
                "system_message_generate_teaching_degree"
            ].format(
                state.get("current_date", ""),
                state.get("search_query", ""),
                tool_message,
            )
        )
        # self._clean_tool_message = None
        return self.generate_helper(state, system_message_generate)

    def juge_answer(self, state: State) -> Dict:
        """Judge the generated answer."""

        logger.debug("[LANGGRAPH][JUDGE ANSWER NODE] Judging the answer")

        class JudgeAnswerResult(BaseModel):
            """Result of answer judgement."""

            new_answer: Optional[str] = Field(
                default=None, description="The new answer to be provided to the user"
            )
            binary_score: Literal["yes", "no"] = Field(
                description="The answer is correct or not"
            )
            reason: str = Field(
                description="Back up your decision with a short explanation"
            )

        llm_with_str_output = self._llm.with_structured_output(JudgeAnswerResult)
        prompt = PromptTemplate(
            template="""
        You are tasked with detecting hallucinations in an agent generated answer. 
        Follow these guidelines:

            1. **Verifiability Assessment**: Review the answer comprehensively. If every aspect of the answer can be verified against the provided context (tool messages), assign a score of 'yes' and back up your assessment (provide a justification).
            2. Identification of Errors: If any of what is stated in the answer does not follow from the provided context (tool messages),  assign a score of 'no'. Explain the discrepancies you identified and state that asnwer is a hallucination. 
            3. Correction Generation: For any incorrect answers, create a new and accurate response that strictly aligns with the information derived from the context. Ensure this revised answer is clear, concise, and fully substantiated by the original data.

            Proceed with the evaluation based on these criteria.
        
            
            ### AI Answer (To be evaluated):
            {answer}
            ### Context (From the tools):
            {context}
            ### User Query:
            {question}
            
            """,
            input_variables=["answer", "context", "question"],
        )
        chain = prompt | llm_with_str_output
        response = chain.invoke(
            {
                "question": state["user_initial_query"],
                "context": [
                    m.content + "\n\n"
                    for m in state["messages"]
                    if isinstance(m, ToolMessage)
                ],
                "answer": state["messages"][-1].content,
            }
        )

        if response.binary_score.lower() == "no":
            # serve new answer
            self._curated_answer = response["new_answer"]
        else:
            # serve the original answer
            self._curated_answer = state["messages"][-1].content

        return {}


class CampusManagementOpenAIToolsAgent(BaseModel, GraphNodesMixin, GraphEdgesMixin):

    # Singleton instance
    # _instance: ClassVar[Optional["CampusManagementOpenAIToolsAgent"]] = None

    _tools_by_name: List[BaseTool] = PrivateAttr(default=None)

    # --------------OpenaAI---------------###
    # _llm: ChatOpenAI = PrivateAttr(default=None)
    # faster llm used for e.g., summarization
    _llm_optional: ChatOpenAI = PrivateAttr(default=None)
    # important: the code uses function calling as opposed to tool calling. (DEPENDS ON THE MODEL and how it was fine tuned)
    # _llm_with_tools: ChatOpenAI = PrivateAttr(default=None)
    # _llm_answer_grader: ChatOpenAI = PrivateAttr(default=None)
    # ----------------Google--------------###
    _llm: ChatGoogleGenerativeAI = PrivateAttr(default=None)
    _llm_with_tools: ChatGoogleGenerativeAI = PrivateAttr(default=None)
    # _llm_optional: ChatGoogleGenerativeAI = PrivateAttr(default=None)

    language: str = Field(default=settings.language)
    # TODO should not be a private attribute
    _graph: StateGraph = PrivateAttr(default=None)
    _chat_history: List[Dict] = PrivateAttr(default=[])
    _prompt_length: int = PrivateAttr(default=None)
    _agent_direct_msg: str = PrivateAttr(default=None)
    _visited_links: List[str] = PrivateAttr(default=[])
    _visited_docs: ReferenceRetriever = PrivateAttr(default=ReferenceRetriever())

    def __init__(self, **data):
        # data: key-value pairs passed through the run method, e.g., CampusManagementOpenAIToolsAgent.run(language='Deutsch')
        if not self.__dict__:
            super().__init__(**data)
            logger.debug(f"Language set to: {self.language}")

            # self._llm = llm()
            self._llm = llm_gemini()
            self._llm_optional = llm_optional()
            # self._llm_optional = llm_gemini()
            # self._reasoning_llm = reasoning_llm()

            tools = GraphNodesMixin.create_tools()
            self._tools_by_name = {tool.name: tool for tool in tools}
            # important: the code uses function calling as opposed to tool calling. (DEPENDS ON THE MODEL and how it was fine tuned)
            # self._llm_with_tools = self._llm.bind_tools(tools)
            self._llm_with_tools = self._llm.bind_tools(tools)
            # self._llm_with_tools = self._reasoning_llm.bind_tools(tools)
            self._prompt_length = get_prompt_length()
            self._create_graph()

    def shorten_conversation_summary(self, summary: str) -> str:
        """Shorten the conversation summary if it exceeds the maximum token limit."""

        logger.warning(
            f"[LANGGRAPH][SHORTEN CONVERSATION SUMMARY] Summary length: {len(summary)}"
        )
        template = translate_prompt()["shorten_conversation_summary"]

        prompt = PromptTemplate(template=template, input_variables=["summary"])
        chain = prompt | self._llm_optional

        response = chain.invoke({"summary": summary})

        return response

    def summarize_conversation(
        self, messages: List[BaseMessage], previous_summary: str = None
    ) -> str:
        # TODO only summarize if the AI message is greater than a certain number of tokens

        if previous_summary:
            template = translate_prompt()["summarize_conversation_previous"]
        else:
            template = translate_prompt()["summarize_conversation"]

        prompt = PromptTemplate(
            template=template, input_variables=["messages", "previous_summary"]
        )
        chain = prompt | self._llm_optional

        # Prepare the arguments based on previous_summary availability
        invoke_args = {"messages": messages}
        if previous_summary:
            invoke_args["previous_summary"] = previous_summary

        response = chain.invoke(invoke_args)
        # google models
        response_text = response.text
        # openai
        # response_text = response.content
        tokens_response = self._llm_optional.get_num_tokens(response_text)
        # To prevent the conversation summary from being too long, we can shorten it
        if tokens_response > MAX_TOKEN_SUMMARY:

            logger.warning(
                f"Conversation Summary is too long ({tokens_response} tokens)"
            )
            response = self.shorten_conversation_summary(response_text)

        return f"**Summary of conversation earlier:** {response_text}"

    def _create_graph(self):
        graph_builder = StateGraph(State)

        graph_builder.add_node("agent_node", self.agent_node)

        graph_builder.add_node("tool_node", self.tool_node)
        graph_builder.add_node("judge_node", self.judge_node)
        graph_builder.add_node("rewrite", self.rewrite)  # Re-writing the question
        graph_builder.add_node(
            "generate", self.generate
        )  # Generating a response after we know the documents are relevant
        # Call agent node to decide to retrieve or not
        graph_builder.add_node("generate_application", self.generate_application)
        graph_builder.add_node(
            "generate_teaching_degree_node", self.generate_teaching_degree_node
        )
        # graph_builder.add_node("judge_answer", self.juge_answer)
        graph_builder.add_edge(START, "agent_node")

        graph_builder.add_conditional_edges(
            "judge_node",
            self.judge_agent_decision,
            {"agent_node": "agent_node", END: END},
        )

        # Decide whether to retrieve
        graph_builder.add_conditional_edges(
            "agent_node",
            # Assess agent decision
            self.route_tools,
            {
                # Translate the condition outputs to nodes in our graph
                "tool_node": "tool_node",
                "judge_node": "judge_node",
            },
        )

        # Edges taken after the `action` node is called.
        graph_builder.add_conditional_edges(
            "tool_node",
            # Assess agent decision
            self.grade_documents,
            {
                "generate": "generate",
                "rewrite": "rewrite",
                "generate_application": "generate_application",
                "generate_teaching_degree_node": "generate_teaching_degree_node",
            },
        )
        graph_builder.add_edge("generate", END)
        graph_builder.add_edge("rewrite", "agent_node")
        graph_builder.add_edge("generate_application", END)
        graph_builder.add_edge("generate_teaching_degree_node", END)

        self._graph = graph_builder.compile(debug=DEBUG)

    def compute_search_num_tokens(self, search_result_text: str) -> int:

        search_result_text_tokens = self._llm.get_num_tokens(search_result_text)

        return search_result_text_tokens

    def compute_internal_tokens(self, query: str) -> int:
        # extract the chat history from the memory
        # TODO BUG: Agent's scratchpad tokens are not being counted (fix sum(count_tokens_history) * 2)
        # history = self._agent_executor.memory.dict()["chat_memory"][
        #     "messages"
        # ]  # this is a list [{'content':'', 'additional_kwargs':{},...}, {}...]
        # history = self._get_chat_history()

        count_tokens_history = [
            self._llm.get_num_tokens(c["content"]) for c in self._chat_history
        ]
        # TODO multiply by 2 to account for agent's scratchpad (Improvement: use tokenization algorithm to count tokens)
        internal_tokens = (
            sum(count_tokens_history) * 2
            + self._prompt_length
            + self._llm.get_num_tokens(query)
        )
        return internal_tokens

    def __call__(self, input: str) -> Union[str, Dict]:
        """Process user input and generate response.

        Args:
            input: User input text

        Returns:
            Union[str, Dict]: Generated response or error message
        """
        from src.chatbot.prompt.prompt_date import get_current_date

        thread_id = uuid.uuid4()
        config = {
            "configurable": {"thread_id": thread_id},
            "recursion_limit": settings.application.recursion_limit,
        }
        prompt = get_system_prompt(
            messages=[],
            user_input=input,
            current_date=get_current_date(settings.language.lower()),
        )

        try:
            response = self._graph.invoke(
                {
                    "messages": prompt,
                    "user_initial_query": input,
                },
                config=config,
            )

            # returns last message content which is the AI message
            return response["messages"][-1].content

        except Exception as e:
            logger.exception(
                f"[LANGGRAPH] An error occurred while generating response: {e}"
            )
            return {
                "output": "An error has occurred while trying to connect to the data source or APIs. Please try asking the question again."
            }

    @classmethod
    def run(cls, *args, **kwargs) -> "CampusManagementOpenAIToolsAgent":
        """Create and return an instance of the agent.

        Returns:
            CampusManagementOpenAIToolsAgent: Configured agent instance
        """
        instance = cls(*args, **kwargs)
        return instance


if __name__ == "__main__":
    from src.chatbot.prompt.main import get_system_prompt
    from src.chatbot.prompt.prompt_date import get_current_date

    graph = CampusManagementOpenAIToolsAgent.run()

    def print_graph(graph, filename="graph.png"):
        """Print the conversation graph as a PNG image.

        Args:
            graph: Graph to visualize
            filename: Output filename
        """
        from IPython.display import Image, display

        try:
            png_data = graph.get_graph().draw_mermaid_png()
            with open(filename, "wb") as f:
                f.write(png_data)
            display(Image(filename))
        except Exception as e:
            print(f"An error occurred: {e}")

    # print_graph(graph._graph)
    async def _execute_graph():
        thread_id = uuid.uuid4()
        config = {
            "configurable": {"thread_id": thread_id},
            "recursion_limit": settings.application.recursion_limit,  # This amounts to two laps of the graph # https://langchain-ai.github.io/langgraph/how-tos/recursion-limit/
        }
        current_date = get_current_date(settings.language.lower())
        conversation_summary = ""
        history = []
        user_input = ("Wo liegt der NC bei Sport?",)
        system_user_prompt = get_system_prompt(
            conversation_summary, history, user_input, current_date
        )
        response = await graph._graph.ainvoke(
            {
                "messages": system_user_prompt,
                "message_history": history,
                "user_initial_query": user_input,
                "current_date": current_date,
            },
            config=config,
        )
        print()

    asyncio.run(_execute_graph())

    def stream_graph_updates(user_input: str) -> str:
        """Stream updates from graph processing.

        Args:
            user_input: User query to process

        Returns:
            str: Final response
        """
        final_answer = ""
        prompt = get_system_prompt([("user", user_input)])
        for msg_chunk, metadata in graph.stream(
            {"messages": prompt},
            config=config,
            stream_mode="messages",
        ):
            if (
                msg_chunk.content
                and not isinstance(msg_chunk, HumanMessage)
                and metadata["langgraph_node"] == "final_answer"
            ):
                final_answer = final_answer + msg_chunk.content
                print(msg_chunk.content, end="|", flush=True)
        return final_answer

    response = stream_graph_updates(user_input)
    stream_graph_updates("Tell me about the computer science program at the uni?")
    print("Done")


# "As a grader, your task is to evaluate whether an LLM generated answer effectively addresses and resolves a user's query while being based on the retrieved information. Assign a binary score:
# 'yes' if the answer fulfills both criteria (it resolves the user query
# and is grounded in the retrieved information) or 'no' if it fails to meet either or both criteria."
